### ISSUE TITLE
Terminal output not shared

### ISSUE THREAD

**Issue by HalbardHobby** [LongLiveCHIEF/wsl2-docker-for-win#12]
Hi,

I used your tutorial, and it worked micracles, allowing me not to depend on virtual machines to use docker. Still, at first I thought it didn't work because the commands

`docker run docker/whalesay cowsay Hello-World!`
`docker run hello-world`

didn't show any of the usual output. On closer inspection it worked just as it was supposed to. The only thing was that the output wasn't printed to the windows terminal.

**Comment by LongLiveCHIEF** [comment]
Make sure the terminal you are using is tty capable and that you're using the `-it` flags.
