### ISSUE TITLE
Add docs for autostarting docker service

### ISSUE THREAD

**Issue by LongLiveCHIEF** [LongLiveCHIEF/wsl2-docker-for-win#2]
I've been able to create a `/etc/sudoers.d/docker.sudoers` file with the content:

```
%docker ALL=(root) NOPASSWD: /etc/init.d/docker start stop restart status
```
Which allows me to run:

```
wsl service start docker
```
To start the docker service.  The next option from here is probably to create a Task to run this command after user logs in.

Either way, need to document the 2 steps above, and the steps for auto-starting via Windows side of things.

*Note:*, I'm also going to look into ways to open a WSL feature request to add a `[autostart]` option to `/etc/wsl.conf` file.  So far have just [tweeted to Ben Hillis](https://twitter.com/LongLiveCHIEF/status/1168211788950843392) about this to see what he thinks

**Comment by edwinvrgs** [comment]
I can help with the docs 😄
