### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by levicrews** [LongLiveCHIEF/wsl2-docker-for-win#6]
I'm running Ubuntu 18.04.3 with WSL2 on Windows build 18999. I followed the instructions, but when I ran `docker version` at the end, I got
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by LongLiveCHIEF** [comment]
Are you sure you ran the [enable and start the docker daemon](https://github.com/LongLiveCHIEF/wsl2-docker-for-win#enable-and-start-the-docker-daemon) steps?

If so, what is the output when running `sudo service docker status`?

**Comment by levicrews** [comment]
```
levicrews@LAPTOP-HK10G6NK:~$ sudo service docker enable
Usage: service docker {start|stop|restart|status}
levicrews@LAPTOP-HK10G6NK:~$ sudo service docker start
 * Starting Docker: docker                                                                         [ OK ]
levicrews@LAPTOP-HK10G6NK:~$ sudo service docker status
 * Docker is not running
levicrews@LAPTOP-HK10G6NK:~$
```

**Comment by LongLiveCHIEF** [comment]
Are you using wsl2 or wsl1?

**Comment by LongLiveCHIEF** [comment]
What I find is interesting is that when you ran the `enable` command it gave you the "command not recognized" message. :thinking:

I might have to dig a little bit more into `19.03.4`. I tested on `19.03.1` and `enable` was supported with the init script.

**Comment by levicrews** [comment]
Yes, I'm running wsl2.
```
PS C:\Users\levic> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

**Comment by LongLiveCHIEF** [comment]
@levicrews I added some additional steps to the install instructions, and fixed some things that have changed (enable no longer a valid command). I think one change in particular might fix your issue.

Can you run `sudo apt-get install containerd.io`. Also, I updated the cli package to `docker-ce-cli`, so you might want to make sure that was installed also.

Finally, can you verify that you have the `"experimental": true` set in `/etc/docker/daemon.json` ?

**Comment by LongLiveCHIEF** [comment]
The release of `19.03.4` split up the client and container runtime to different packages, so when @levicrews ran through these instructions, he got `19.03.41 instead of `19.03.1` (which was latest when I wrote this guide). As a result, he (ar anyone who ran through the _old_ instructions on or after **October 17, 2019` didn't get the engine runtime.

For anyone who had that issue, installing `containerd.io` _should_ fix the issue for you.

See the excerpt below, taken from the [release notes for docker 19.03.4](https://docs.docker.com/engine/release-notes/)

> Note: The client and container runtime are now in separate packages from the daemon in Docker Engine 18.09. Users should install and update all three packages at the same time to get the latest patch releases. For example, on Ubuntu: sudo apt install docker-ce docker-ce-cli containerd.io. See the install instructions for the corresponding linux distro for details.)

**Comment by levicrews** [comment]
Unfortunately, this still didn't work for me:
```
Documents:~$ sudo service docker start
 * Starting Docker: docker                                                                      [ OK ] 
Documents:~$ sudo service docker status
 * Docker is not running
Documents:~$ sudo service docker stop
 * Stopping Docker: docker
start-stop-daemon: warning: failed to kill 1882: No such process
No process in pidfile '/var/run/docker-ssd.pid' found running; none killed.
```

**Comment by LongLiveCHIEF** [comment]
interesting that it positively identified a PID for the docker service. :thinking:

Do you have any hunches of your own? I'm kinda left with no where else to go with this one. I was able to reproduce your issue on a fresh install, and then running the install for containerd.io fixed it for me.

**Comment by terebentina** [comment]
The problem I had was with the comment in `docker.json`. Remove the comment and restart the daemon.

**Comment by LongLiveCHIEF** [comment]
@terebentina thank you for pointing that out. That comment was intended to be an enhancement to the documentation and I didn't expect anyone to copy it.

I broke a golden rule of documentation: "don't make any assumptions on behalf of the reader".

I'll fix this ASAP!
