### ISSUE TITLE
Error in /etc/docker/daemon.json

### ISSUE THREAD

**Issue by gianfryBear** [LongLiveCHIEF/wsl2-docker-for-win#9]
There is a type mistake in the file content: "," is missing between arguments.
It take me a while to get why the docker won't running after the following step by step other steps.

So this is the original:
{
    "hosts": ["unix://", "tcp://0.0.0.0:2375"]
    "experimental": true
}
which should be:
{
    "hosts": ["unix://", "tcp://0.0.0.0:2375"],
    "experimental": true
}
Hope it will be helpful to others =)

**Comment by LongLiveCHIEF** [comment]
Thanks for reporting! do you want to do a Pull Request and get credit, or is it ok if I fix it?

**Comment by gianfryBear** [comment]
Wow, tnk for the proposal but I prefer to leave it to you =)
